name: Repositories sync

on:
    pull_request:
        paths:
            - 'SHARED-README.md'
            - 'repositories.json'
            - 'sync.ts'

jobs:
    sync-local-repository:
        name: Sync local README & repositories
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Sync local README
              run: npx ts-node sync.ts local

            - name: Sync repository descriptions
              run: npx ts-node sync.ts descriptions

            - name: Commit changes to repository
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: sync shared README content
                  commit_options: '--no-verify --signoff'
                  file_pattern: README.md repositories.json
                  commit_author: GitHub Actions <actions@github.com>
