name: Readme sync

on:
  pull_request:
    types: [closed]
    paths:
      - 'SHARED-README.md'
      - 'repositories.json'

jobs:

  sync-remote-readme:
    name: Sync all World ID READMEs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Sync remote READMEs
        env:
          GITHUB_TOKEN: ${{ secrets.WLD_ID_SYNC }}
        run: npx ts-node sync.ts remote